name: CI
on:
  push:
    branches: [ "render" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Environment Variables
        run: |
          IMAGE=https://i.ibb.co/nqh56Hcw/white.png
          MAXPLAYERS=45
          MOTD=&bThis server is hosted by &4&l&nv-jXe!&r\n               &e&l&ntinyurl.com/vv-jXe
          RENDER=https://velocity-javaxeagler.onrender.com
          SECRET=A_VERY_SECURE_SECRET
          SERVER=0.0.0.0:14457

      - name: Start ./main.sh
        run: bash main.sh
